# To run: conda env create -f environment.yml
name: diffdiffdepth
channels:
    - conda-forge
    - pytorch
    
dependencies:
    - python=3.6
    - pip
    - scikit-image
    - scipy
    - cudatoolkit=10.1
    - pytorch=1.5.1
    - torchvision=0.6.1
    - numpy
    - configargparse

